-- Import case studies from static JSON into projects table
INSERT INTO projects (
  slug,
  title,
  category,
  location,
  summary,
  description,
  featured_image,
  year,
  duration,
  project_size,
  publish_state,
  featured
) VALUES 
(
  'downtown-office-renovation',
  'Downtown Office Tower Renovation',
  'Commercial',
  'Toronto, ON',
  'Modernize a 15-story office building''s interior while maintaining daily operations with 200+ employees.',
  E'Implemented a phased, after-hours approach using low-VOC materials for occupied spaces.\n\n**Results:**\n- Zero disruption to business operations\n- Completed 2 weeks ahead of schedule\n- 98% employee satisfaction with new environment\n- 30% reduction in energy costs with new coatings\n\nThis comprehensive renovation included painting all common areas, conference rooms, and private offices across 15 floors. The project required careful coordination with building management to minimize tenant disruption.',
  'case-office-tower.jpg',
  '2024',
  '6 weeks',
  '45,000 sq ft',
  'published',
  true
),
(
  'luxury-condo-restoration',
  'Luxury Waterfront Condo Complex',
  'Residential',
  'Mississauga, ON',
  'Restore exterior stucco and EIFS on a 25-year-old luxury condominium complex while residents remained in their homes.',
  E'Developed a unit-by-unit schedule with resident coordination and implemented complete weatherproofing during work.\n\n**Results:**\n- All 120 units completed on schedule\n- Zero water intrusion incidents\n- 95% resident satisfaction rating\n- Extended building envelope life by 20+ years\n\nThe project involved repairing and refinishing all exterior stucco and EIFS surfaces, addressing water damage, and implementing a new weather barrier system.',
  'case-waterfront-condo.jpg',
  '2024',
  '8 weeks',
  '120 units',
  'published',
  true
),
(
  'heritage-building-restoration',
  'Heritage Building Facade Restoration',
  'Heritage/Commercial',
  'Old Toronto, ON',
  'Restoring a 1920s heritage building''s original stucco facade while meeting modern building codes and preservation guidelines.',
  E'Matched original materials and techniques with modern weatherproofing technology, working closely with heritage consultants.\n\n**Results:**\n- Heritage designation maintained\n- Approved by Toronto Heritage Board\n- 100% authentic appearance restored\n- 50-year warranty on new systems\n\nOriginal stucco samples were analyzed in a lab to match composition. Custom pigments were mixed to achieve the exact original color.',
  'case-heritage-building.jpg',
  '2023',
  '14 months',
  '45,000 sq ft',
  'published',
  true
),
(
  'underground-parking-restoration',
  'Underground Parking Garage Restoration',
  'Commercial',
  'Downtown Toronto, ON',
  'Restore a deteriorating 30-year-old underground parking garage with severe concrete spalling and coating failure while maintaining partial operations.',
  E'Implemented a phased approach with temporary parking solutions, applied advanced epoxy repair systems, and installed high-performance traffic coatings.\n\n**Results:**\n- Extended structure life by 25+ years\n- Improved lighting by 40% with reflective coatings\n- Zero disruption to building operations\n- Completed under budget\n\nThe project involved concrete repair, waterproofing, installation of traffic-rated polyurethane coatings, and line striping across three underground levels.',
  'case-parking-restoration.jpg',
  '2024',
  '10 weeks',
  '85,000 sq ft',
  'published',
  false
),
(
  'high-rise-balcony-restoration',
  'High-Rise Balcony Restoration Project',
  'Residential',
  'Etobicoke, ON',
  'Repair and refinish 200 balconies across a 30-story residential tower with water damage, concrete deterioration, and coating failure.',
  E'Coordinated with residents for access, implemented comprehensive concrete repairs, applied waterproof membrane systems, and installed decorative coatings.\n\n**Results:**\n- All 200 balconies completed on schedule\n- Eliminated water infiltration issues\n- 98% resident satisfaction rating\n- 10-year warranty on all work\n\nEach balcony received structural assessment, concrete repair, crack injection, waterproof membrane installation, and a final decorative coating system.',
  'case-balcony-restoration.jpg',
  '2024',
  '12 weeks',
  '200 balconies',
  'published',
  false
),
(
  'retail-plaza-transformation',
  'Retail Plaza Exterior Transformation',
  'Commercial',
  'Vaughan, ON',
  'Modernize a dated 1980s retail plaza exterior to attract new tenants while keeping all existing stores operational during the work.',
  E'Complete facade makeover with new EIFS system, accent metal panels, modern color scheme, and enhanced architectural details.\n\n**Results:**\n- Increased property value by 35%\n- Attracted 5 new premium tenants\n- Zero complaints from existing tenants\n- Featured in local architecture magazine\n\nThe project included removal of old stucco, installation of new insulated EIFS system, decorative metal cladding accents, new signage, and comprehensive painting.',
  'case-retail-plaza.jpg',
  '2023',
  '8 weeks',
  '60,000 sq ft',
  'published',
  false
),
(
  'school-interior-renovation',
  'Elementary School Interior Renovation',
  'Institutional',
  'Brampton, ON',
  'Refresh a 40-year-old elementary school interior during summer break with strict safety and schedule requirements.',
  E'Used zero-VOC paints, implemented accelerated schedule, coordinated with school board specifications, and ensured completion before school year.\n\n**Results:**\n- Completed 5 days ahead of schedule\n- 100% compliance with safety standards\n- Positive feedback from teachers and parents\n- No odors or air quality issues on opening day\n\nPainted all classrooms, hallways, gymnasium, cafeteria, and administrative offices using low-VOC materials. Included decorative murals in common areas.',
  'case-school-interior.jpg',
  '2023',
  '6 weeks',
  '35,000 sq ft',
  'published',
  false
),
(
  'industrial-warehouse-coating',
  'Industrial Warehouse Floor Coating',
  'Industrial',
  'Mississauga, ON',
  'Install a high-performance floor coating system in an active distribution warehouse without shutting down operations.',
  E'Worked overnight shifts in sections, used fast-cure epoxy systems, and coordinated closely with warehouse operations to maintain workflow.\n\n**Results:**\n- Zero operational downtime\n- Floor ready for traffic in 24 hours per section\n- Increased floor brightness by 60%\n- 15-year durability rating\n\nApplied industrial-grade epoxy coating system with chemical resistance, anti-slip additives, and high-durability topcoat. Included line striping and safety markings.',
  'case-warehouse-floor.jpg',
  '2024',
  '4 weeks',
  '120,000 sq ft',
  'published',
  false
)
ON CONFLICT (slug) DO NOTHING;